### ISSUE TITLE
MS4 Feedback

### ISSUE THREAD

**Issue by Iadel95** [ubco-W2022T2-data301/project-group-group31#2]
## Feedback for Group 31

1. Notes from [Islam] on Feedback on the analysis:

Analysis 1:

- Good job.
- [x] #3

Analysis 2:

- Good job.
- [x] #4
- [x] #5
- [x] #6
- [x] #7

Analysis 2:
- Good job.
- [x] #8

## Contracted Grade

1. What is your contracted grade?

- A

2. Are you on track to satisfy all the requirements of your contracted grade?

- Yes, work isn't done but you're on the right track.

**Comment by LoganMarsha11** [comment]
Answered milestone 4 feedback
